source 'https://github.com/LeiZong/ZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ZZSpecialKit_Example' do
  pod 'ZZSpecialKit', :path => '../'

  target 'ZZSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
